[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "debug-ff-macos-delete"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

git-init = """
git config --global user.email "you@example.com" && \
git config --global user.name "Your Name"
"""

clone = """
rm -rf ff && \
git clone https://github.com/hep-packaging-coordination/ff.git && \
cd ff && \
git cherry-pick 712ef3c8c1632a538526ece64be05a3763516b34
"""

build = """
cd ff && \
sed -i "s|/user/gj/lib/|$CONDA_PREFIX/share/ff/ |g" src/ff/ffinit.f && \
sed -i "s|/usr/local/ff/|$CONDA_PREFIX/share/ff/ |g" src/ff/ffinit.f && \
cd src/ff && \
make install FC=$FC FFLAGS="$FFLAGS -std=legacy -ffixed-line-length-none" DEST=$CONDA_PREFIX/lib --jobs=10 && \
mkdir -p $CONDA_PREFIX/include/ff && \
cp *.h $CONDA_PREFIX/include/ff && \
mkdir -p $CONDA_PREFIX/share/ff && \
cp *.dat $CONDA_PREFIX/share/ff/
"""

test = """
$FC ./ff/src/ff/npointes.f -o npointes $FFLAGS -I$CONDA_PREFIX/include/ff $LDFLAGS -lff && \
./npointes
"""

[dependencies]
fortran-compiler = ">=1.8.0,<2"
make = ">=4.4.1,<5"
libtool = ">=2.4.7,<3"
git = ">=2.47.1,<3"
sed = ">=4.7,<5"
