name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: [ubuntu-latest, macos-13, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

    - name: OS info
      run: uname -a

    - name: List installed packages
      run: pixi list

    - name: Build
      run: |
        pixi run clone
        pixi run build

    - name: Test
      run: |
        pixi run test
